### ISSUE TITLE
Updating the Jupyter notebook version of bike tutorial

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminus-tutorials#21]
The Jupyter notebook version of bike tutorial is not up to date with the latest version of TerminusDB and Python client 😞 could you please give us a hand? 💪🏻

1) Install the latest versions of TerminusDB following the instructions [here](https://github.com/terminusdb/terminusdb-quickstart/blob/master/README.md). You will need to have Docker. 🐳

2) Create a new Python environment (optional), install the [Python client](https://github.com/terminusdb/terminusdb-client-python#installation) (`pip install terminusdb-client[dataframe]`) and Jupyter notebook (`pip install notebook`)

3) Referring to [this code](https://github.com/terminusdb/terminus-tutorials/blob/master/bike-tutorial/python/bike-tutorial.py), update the code in the [tutorial notebook here](https://github.com/terminusdb/terminus-tutorials/blob/master/bike-tutorial/python/Create%20TerminusDB%20Graph%20with%20Python%20Client.ipynb) and make sure it works. ✅

4) Clear all output in the Jupyter notebook before you commit 🧽

5) When you make a PR, link to this issue by adding `close #21 ` in the comment of the PR.

**Comment by mts310** [comment]
Hey all just to let you know I will look into this.
